### ISSUE TITLE
APIs required [urgently]

### ISSUE THREAD

**Issue by adarshtri** [Ayushi61/Classroom-Bot#24]
We need the following APIs in the order they are mentioned:

- [x] **/course** (GET,POST,PUT,PATCH,DELETE whichever all applicable to move fast)

- [x] **/student** (GET,POST,PUT,PATCH,DELETE whichever all applicable to move fast)

- [x] **/group** (GET,POST,PUT,PATCH,DELETE whichever all applicable to move fast)

I guess we are close just need some beautification of things in the APIs. The whole idea is to create all the endpoints perfectly one by one and put a commit and let us know after done with every endpoint @prithvipatl @Ayushi61

**Comment by prithvipatl** [comment]
Kindly review #26
